name: Build fatropy wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # windows and macos not working yet
        os: [ubuntu-latest]
        

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0
        env:
           # for now only build specific versions
           CIBW_BUILD: cp38-manylinux_x86_64 
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
           package-dir: ./fatropy
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  install_wheel:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cibw-wheels-ubuntu-latest-0  # Adjust the name based on the actual artifact name
          path: wheel  # Specify the directory where you want to download the artifact

      - name: Install the wheel package
        run: pip install ./wheel/*.whl
