name: Build fatropy wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # windows and macos not working yet
        os: [ubuntu-latest, windows-latest]
        

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Conditionally set up MinGW or Clang on Windows
      - name: Set up MinGW
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys@v2
        with:
          mingw_arch: x86_64
          install: mingw-w64-x86_64-toolchain
          
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0
        env:
           # for now only build specific versions
           CIBW_BUILD: cp38-win_amd64 cp38-manylinux_x86_64 cp38-macosx_universal2

           CIBW_ENVIRONMENT_WINDOWS: >
                CMAKE_ARGS="-G "MinGW Makefiles" -DBLASFEO_TARGET=X64_INTEL_HASWELL -DBLASFEO_CROSSCOMPILING=ON;$CMAKE_ARGS"
                

           # only build linux x86_64
           CIBW_ARCHS_LINUX: native
           # Skip 32-bit builds
           CIBW_SKIP: "*-musllinux*"
           

        with:
           package-dir: ./fatropy
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

